// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Future_Fashion_API.attributes;
using System;
using System.Collections.Generic;

namespace Future_Fashion_API.entities
{
    public partial class TblCategory
    {

        [PrimaryKey]
        public int CatId { get; set; }
        public string CatName { get; set; }

       
    }
}