// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Future_Fashion_API.entities
{
    public partial class TblBrands
    {
       

        public int BrandId { get; set; }
        public string Name { get; set; }

       
    }
}