// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Future_Fashion_API.attributes;
using System;
using System.Collections.Generic;

namespace Future_Fashion_API.entities
{
    public partial class TblOrders
    {
        [PrimaryKey]
        public int OrderId { get; set; }
        public int? UserId { get; set; }
        public string Email { get; set; }
        public decimal? CartAmount { get; set; }
        public decimal? CartDiscount { get; set; }
        public decimal? TotalPaid { get; set; }
        public string PaymentType { get; set; }
        public string PaymentStatus { get; set; }
        public DateTime? DateOfPurchase { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
        public string OrderStatus { get; set; }
        public string OrderNumber { get; set; }

    }
}