// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Future_Fashion_API.Models
{
    public partial class TblPurchase
    {
        public int PurchaseId { get; set; }
        public int? UserId { get; set; }
        public string PidsizeId { get; set; }
        public decimal? CartAmount { get; set; }
        public decimal? CartDiscount { get; set; }
        public decimal? TotalPayed { get; set; }
        public string PaymentType { get; set; }
        public string PaymentStatus { get; set; }
        public DateTime? DateOfPurchase { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public string MobileNumber { get; set; }

    }
}