// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Future_Fashion_API.attributes;
using System;
using System.Collections.Generic;

namespace Future_Fashion_API.entities
{
    public partial class TblProducts
    {
        [PrimaryKey]     
        
        public int Pid { get; set; }
        public string Pname { get; set; }
        public decimal? Pprice { get; set; }
        public decimal? PselPrice { get; set; }
        public int? PbrandId { get; set; }
        public int? PcategoryId { get; set; }
        public int? PsubCatId { get; set; }
        public int? Pgender { get; set; }
        public string Pdescription { get; set; }
        //public string PproductDetails { get; set; }
        //public string PmaterialCare { get; set; }
        //public int? FreeDelivery { get; set; }
        //public int? _30dayRet { get; set; }
        //public int? Cod { get; set; }

        
    }
}