// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Future_Fashion_API.attributes;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Future_Fashion_API.entities
{
    public partial class TblProductImages
    {
        [PrimaryKey]
        public int Pimgid { get; set; }
        public int? Pid { get; set; }
        public string Name { get; set; }
        public string Extention { get; set; }

        [PropertyIgnore]
        public string ImageBase64 { get; set; }

    }
}