// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Future_Fashion_API.entities
{
    public partial class TblSubCategory
    {
       

        public int SubCatId { get; set; }
        public string SubCatName { get; set; }
        public int? MainCatId { get; set; }

        
    }
}